### ISSUE TITLE
چهار پنج ساعتی هست که سایت و شبیه ساز برام نمیاد.

### ISSUE THREAD

**Issue by thinkingparticle** [SharifAIChallenge/AIC18_Graphics#10]
سلام . 
چهار پنج ساعتی هست که سایت و شبیه ساز برام نمیاد. فقط مشکله منه یا برای همه است؟

**Comment by ali-behjati** [comment]
این مشکل خیلی عجیبه، لطفا اگه هنوزم پابرجاس بفرمایین، تا دقایقی دیگه
ایشالله نسخه جدید نمایشگر بازی منتشر میشه.

**Comment by thinkingparticle** [comment]
درست شده برادر
با تچکر
