### ISSUE TITLE
Storms are shown in incorrect position

### ISSUE THREAD

**Issue by mdibaiee** [SharifAIChallenge/AIC18_Graphics#13]
Hi,

Using the CPP client, I create a storm using the following code:

```cpp
  world->create_storm(cells[0]->get_location().get_y(), cells[0]->get_location().get_x());
```

Though the storm does work and destroy the units in the correct cell, the effect shown in the game viewer is in opposite order of coordinates, i.e. the effect is shown at (x, y) instead of (y, x).

**Comment by mahdisn76** [comment]
Yes i have experienced the same problem:|
        game.createStorm(0,10);
        game.plantBean(1,10);
        game.createArcherTower(1,2,10);
![image](https://user-images.githubusercontent.com/24755996/36353414-66541100-14db-11e8-9203-aeb00fae55e2.png)

**Comment by thinkingparticle** [comment]
take a look at #11 issue. the x & y directions are mirrored in game viewer.
