### ISSUE TITLE
Cuts maps in large map

### ISSUE THREAD

**Issue by nekooei** [SharifAIChallenge/AIC18_Graphics#14]
When create custom map with large size for example 30*30, in game viewer Map shows Catted from an edge!
showing in attachment
also I attached my simple map

[iranina-park-map.zip](https://github.com/SharifAIChallenge/AIC18_Graphics/files/1732695/iranina-park-map.zip)

![image](https://user-images.githubusercontent.com/12533428/36327402-760f8146-1356-11e8-93cf-c2b887b0b177.png)

**Comment by ali-behjati** [comment]
This issue is fixed in this release.
