### ISSUE TITLE
Fatal error in offline versions of `game_viewer` and `map_maker`... 404!

### ISSUE THREAD

**Issue by saeidscorp** [SharifAIChallenge/AIC18_Graphics#15]
These two won't run properly as they seem to lack the required files in the `static` subdirectory.

No CSS and JS files present in `statics` directory, yet the `index.html` tries to fetch them and causes a whole bunch of 404s!

To name a few:

```
http://localhost:8000/static/semantic/semantic.rtl.min.css -> 404
http://localhost:8000/static/css/styles.css -> 404
http://localhost:8000/static/js/jquery.min.js -> 404
http://localhost:8000/static/semantic/semantic.min.js -> 404
http://localhost:8000/static/js/scripts.js -> 404
```

Even the directory names are inconsistent, HTML tries to load them from `static`, where the directory structure contains a `statics` folder.

Both the release archives (and source code release), and the git master seem to be the case.

Any Ideas? What am I missing?!
TIA.

**Comment by ali-behjati** [comment]
These graphics are mainly released for the website and these scripts are
for UI. Their lack of existence shouldn't make any difference. (It only
affects the first page which you upload your log file)
