### ISSUE TITLE
باگ گردباد

### ISSUE THREAD

**Issue by AM1648** [SharifAIChallenge/AIC18_Graphics#16]
گردباد در نمایشگر به صورت متقارن نسبت به خط عمودی نمایش داده میشود در حالی که تاثیر آن روی سرباز ها صحیح است

**Comment by ali-behjati** [comment]
منظور شما را متوجه نشدم. می‌شود دقیق‌تر بیان کنید؟
اگر اشتباه نکنم در گردباد ما گردباد را از همان خانه مرکز که گفته شده نمایش می‌دهیم. با اینکه شکل گردباد دایره‌ای هست اما در بازی به شکل منهتنی سربازها را می‌کشد.

**Comment by AM1648** [comment]
![photo_2018-02-22_16-35-28](https://user-images.githubusercontent.com/20911858/36540150-848fd97c-17ee-11e8-92a3-41b9125a52c2.jpg)
نمایشگر گردباد ها را به صورتی که در شکل میبینید قرینه نشان میدهد و اتفاقا سرباز های عادی واقع در محل واقعی گردباد را هم نابود میکند

**Comment by s-omranpour** [comment]
مشکل مکان گرد باد در آپدیت بعدی مرتفع میشه. اما در در مورد از بین رفتن یونیت ها مشکلی وجود نداره. ممنون بابت اطلاع این باگ!

**Comment by ali-behjati** [comment]
ورژن بعدی هم به زودی ریلیز می‌شه. 
من می‌بندم این ایشو رو.
