### ISSUE TITLE
An attempt was made to use an object that is not, or is no longer, usable

### ISSUE THREAD

**Issue by mohammadrezza** [SharifAIChallenge/AIC18_Graphics#9]
![screenshot from 2018-02-11 23-19-58](https://user-images.githubusercontent.com/17231359/36077616-05f55a24-0f65-11e8-9e2c-2479cd5773b0.png)
سلام این مشکل چجوری رفع کنم ؟

**Comment by ali-behjati** [comment]
هنوز این مشکل برقراره؟
لطفا اگر در ریلیز جدید نمایشگر هنوز این مشکل وجود داره بفرمایید.
توجه کنید که طبیعی هست که ارور هایی در کنسول داده بشه (ولی بازی به درستی
نمایش داده بشه)
